name: kmeans_env
channels:
  - bioconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20230802.0
  - aioeasywebdav=2.4.0
  - aiohttp=3.8.5
  - aiosignal=1.2.0
  - amply=0.1.6
  - appdirs=1.4.4
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - attmap=0.13.2
  - attrs=23.1.0
  - backcall=0.2.0
  - bcrypt=3.2.0
  - black=23.10.0
  - blas=1.0
  - boltons=23.0.0
  - boto3=1.29.1
  - botocore=1.32.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - cachetools=4.2.2
  - cairo=1.18.0
  - cairomm-1.16=1.16.2
  - certifi=2025.1.31
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.7
  - coin-or-cbc=2.10.10
  - coin-or-cgl=0.60.5
  - coin-or-clp=1.17.7
  - coin-or-osi=0.108.7
  - coin-or-utils=2.11.6
  - coincbc=2.10.10
  - colorama=0.4.6
  - conda=23.9.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - configargparse=1.4
  - connection_pool=0.0.3
  - cryptography=41.0.3
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.3.52
  - cuda-runtime=12.1.0
  - cudatoolkit=11.8.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - datrie=0.8.2
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docutils=0.18.1
  - dpath=2.1.6
  - dropbox=11.36.1
  - eido=0.2.1
  - epoxy=1.5.10
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - expat=2.5.0
  - ffmpeg=4.2.2
  - filechunkio=1.8
  - fmt=10.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.0
  - ftputil=5.0.4
  - gdk-pixbuf=2.42.10
  - gettext=0.21.1
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.37
  - glib=2.78.1
  - glib-tools=2.78.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - google-api-python-client=2.104.0
  - google-auth=2.22.0
  - google-auth-httplib2=0.1.1
  - google-cloud-storage=2.6.0
  - google-crc32c=1.5.0
  - google-resumable-media=2.4.0
  - googleapis-common-protos=1.56.4
  - graph-tool=2.58
  - graph-tool-base=2.58
  - graphite2=1.3.13
  - grpc-cpp=1.48.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gtest=1.14.0
  - gtk3=3.24.38
  - harfbuzz=8.3.0
  - hicolor-icon-theme=0.17
  - httplib2=0.22.0
  - humanfriendly=10.0
  - icu=73.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=6.1.0
  - iniconfig=1.1.1
  - intel-openmp=2023.1.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jmespath=1.0.1
  - joblib=1.2.0
  - jpeg=9e
  - jsonpatch=1.32
  - jsonpointer=2.1
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libarchive=3.7.2
  - libblas=3.9.0
  - libboost=1.82.0
  - libboost-python=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang13=14.0.6
  - libcrc32c=1.1.2
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.8.0.34
  - libcups=2.3.3
  - libcurand=10.3.4.52
  - libcurl=8.4.0
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libexpat=2.5.0
  - libfaiss=1.7.3
  - libfaiss-avx2=1.7.3
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgirepository=1.78.1
  - libglib=2.78.1
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libmamba=1.5.2
  - libmambapy=1.5.2
  - libnghttp2=1.57.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - librsvg=2.56.3
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libssh2=1.10.0
  - libstdcxx-ng=13.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libvpx=1.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.6.0
  - libxml2=2.11.5
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - logmuse=0.2.6
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.2
  - markdown-it-py=2.2.0
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multidict=6.0.2
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - mysql=5.7.24
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - oauth2client=4.1.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.2.0
  - pango=1.50.14
  - paramiko=2.8.1
  - parso=0.8.3
  - pathspec=0.10.3
  - pcre=8.45
  - pcre2=10.42
  - peppy=0.35.7
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3
  - pixman=0.42.2
  - plac=1.3.4
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - ply=3.11
  - polars=0.19.11
  - prettytable=3.5.0
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pulp=2.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pybind11-abi=4
  - pycairo=1.25.1
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.15.1
  - pygobject=3.46.0
  - pynacl=1.5.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytest=7.4.0
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-irodsclient=1.1.9
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.30.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - reretry=0.11.8
  - rich=13.3.5
  - rpds-py=0.10.6
  - rsa=4.7.2
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - s3transfer=0.7.0
  - setuptools=68.0.0
  - sigcpp-3.0=3.6.0
  - sip=6.7.12
  - six=1.16.0
  - slacker=0.14.0
  - smart_open=5.2.1
  - smmap=4.0.0
  - snakemake=7.32.4
  - snakemake-minimal=7.32.4
  - sparsehash=2.0.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - stone=3.3.1
  - stopit=1.1.2
  - tbb=2021.8.0
  - throttler=1.2.2
  - tk=8.6.12
  - tomli=2.0.1
  - toposort=1.10
  - torchaudio=2.1.0
  - torchvision=0.16.0
  - tornado=6.3.3
  - tqdm=4.66.1
  - tzdata=2023c
  - ubiquerg=0.6.3
  - uritemplate=4.1.1
  - urllib3=1.26.18
  - veracitools=0.1.3
  - wayland=1.22.0
  - wcwidth=0.2.5
  - wheel=0.41.2
  - wrapt=1.14.1
  - x264=1!157.20191217
  - xkeyboard-config=2.40
  - xorg-compositeproto=0.4.2
  - xorg-damageproto=1.2.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.0
  - xorg-libxdamage=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.2
  - xorg-libxrender=0.9.11
  - xorg-libxtst=1.2.3
  - xorg-randrproto=1.5.0
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-util-macros=1.19.3
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.2
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yarl=1.8.1
  - yte=1.5.1
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - aiofiles==24.1.0
      - aiosqlite==0.21.0
      - anyio==4.2.0
      - arch==7.0.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - babel==2.14.0
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - blessed==1.20.0
      - bokeh==3.4.3
      - brokenaxes==0.6.2
      - cloudpickle==3.1.1
      - cmake==3.31.0.1
      - cmdstanpy==1.2.4
      - comm==0.2.1
      - contourpy==1.3.0
      - cramjam==2.9.1
      - cython==0.29.32
      - dashboard==0.0.6
      - dask==2024.8.0
      - databases==0.9.0
      - db-dtypes==1.4.2
      - dbgz==0.5.4
      - dill==0.3.8
      - distanceclosure==0.5
      - distlib==0.3.9
      - duckdb==1.2.1
      - faiss-cpu==1.12.0
      - faiss-gpu==1.7.2
      - fast-hdbscan==0.1.3
      - fastnode2vec==0.0.5
      - fastparquet==2024.11.0
      - fasttext==0.9.3
      - filelock==3.17.0
      - flatbuffers==23.5.26
      - fqdn==1.5.1
      - fsspec==2024.10.0
      - gast==0.5.4
      - gensim==4.3.3
      - gensim-mod==4.3.3
      - geoopt==0.5.1
      - google-api-core==2.24.2
      - google-auth-oauthlib==1.2.0
      - google-cloud-bigquery==3.31.0
      - google-cloud-bigquery-storage==2.30.0
      - google-cloud-core==2.4.3
      - google-cloud-run==0.10.17
      - google-pasta==0.2.0
      - gpustat==1.1.1
      - greenlet==3.1.1
      - grpc-google-iam-v1==0.14.2
      - grpcio==1.71.0
      - grpcio-status==1.62.3
      - h11==0.14.0
      - h5py==3.10.0
      - holidays==0.56
      - httpcore==1.0.4
      - httpx==0.27.0
      - igraph==0.10.2
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - imbalanced-learn==0.12.4
      - imblearn==0.0
      - infomap==2.7.1
      - iopath==0.1.10
      - ipykernel==6.29.3
      - ipympl==0.9.3
      - ipynb==0.5.1
      - ipython==8.18.1
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - jax==0.4.23
      - jaxlib==0.4.23
      - json5==0.9.14
      - jupyter-client==8.6.1
      - jupyter-console==6.6.3
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.2
      - jupyter-server==2.13.0
      - jupyter-server-terminals==0.5.2
      - jupyterlab==4.1.5
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.2
      - jupyterlab-widgets==3.0.10
      - jupyterthemes==0.20.0
      - keras==3.5.0
      - lesscpy==0.15.1
      - libclang==16.0.6
      - linkify-it-py==2.0.3
      - lit==18.1.8
      - llvmlite==0.43.0
      - locket==1.0.0
      - lxml==5.3.1
      - markdown==3.5.2
      - matplotlib==3.6.0
      - mdit-py-plugins==0.4.2
      - mercator==1.0.0
      - mistune==3.0.2
      - ml-dtypes==0.2.0
      - mplcursors==0.6
      - msgpack==1.1.0
      - namex==0.0.8
      - narwhals==1.30.0
      - nbclient==0.10.0
      - nbconvert==7.16.3
      - nbformat==5.10.3
      - networkx==2.8.8
      - nibabel==5.2.0
      - nltk==3.9.1
      - notebook==7.1.2
      - notebook-shim==0.2.3
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==12.535.108
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.8.90
      - nvitop==1.3.2
      - oauthlib==3.2.2
      - openalex-raw==0.3.2
      - openalexapi==0.0.1a0
      - opencv-python==4.9.0.80
      - opt-einsum==3.3.0
      - optree==0.12.1
      - orjson==3.10.16
      - orm==0.2.0.dev1
      - overrides==7.6.0
      - packaging==24.2
      - pandas==2.2.2
      - pandocfilters==1.5.0
      - panel==1.4.5
      - param==2.2.0
      - partd==1.4.2
      - patsy==0.5.3
      - pipenv==2024.4.1
      - plotly==6.0.0
      - polar==0.0.127
      - portalocker==3.0.0
      - powerlaw==1.5
      - prometheus-client==0.19.0
      - prompt-toolkit==3.0.43
      - prophet==1.1.5
      - proto-plus==1.26.1
      - protobuf==4.25.6
      - pyalex==0.15.1
      - pyarrow==19.0.1
      - pybind11==2.13.6
      - pyclustering==0.11.0
      - pyesn==0.0.2
      - pympler==1.1
      - pynndescent==0.5.11
      - python-docx==1.1.2
      - python-graphviz==0.20.3
      - python-json-logger==2.0.7
      - python-louvain==0.16
      - python-multipart==0.0.20
      - python-pptx==1.0.2
      - pytz==2022.7
      - pyviz-comms==3.0.4
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - regex==2024.11.6
      - requests-oauthlib==1.3.1
      - reservoir-computing==0.35.1
      - reservoirpy==0.3.11
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - runipy==0.1.5
      - scikeras==0.13.0
      - scikit-learn==1.5.2
      - scipy==1.13.0
      - seaborn==0.13.2
      - send2trash==1.8.2
      - sniffio==1.3.0
      - soupsieve==2.5
      - sqlalchemy==2.0.38
      - stanio==0.5.1
      - starlette==0.46.0
      - statsmodels==0.14.0
      - sympy==1.14.0
      - tabulate==0.8.9
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0.post1
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.36.0
      - termcolor==2.4.0
      - terminado==0.18.0
      - texttable==1.6.7
      - threadpoolctl==3.5.0
      - tinycss2==1.2.1
      - toolz==1.0.0
      - torch==2.8.0
      - traitlets==5.14.2
      - triton==3.4.0
      - types-python-dateutil==2.8.19.20240106
      - typesystem==0.3.0.dev0
      - typing-extensions==4.12.2
      - uc-micro-py==1.0.3
      - ujson==5.10.0
      - umap-learn==0.5.5
      - uri-template==1.3.0
      - uvicorn==0.34.0
      - virtualenv==20.29.2
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.10
      - xlsxwriter==3.2.2
      - xyzservices==2025.1.0
prefix: /nobackup/gogandhi/miniconda3/envs/kmeans_env
