name: gensim_mod_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _x86_64-microarch-level=4
  - alsa-lib=1.2.13
  - asttokens=3.0.0
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - black=25.1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cairo=1.18.2
  - cairomm=1.16.2
  - cairomm-1.16=1.16.2
  - certifi=2024.12.14
  - cffi=1.17.1
  - click=8.1.8
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.0
  - cpp-expected=1.1.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dbus=1.13.6
  - debugpy=1.8.12
  - decorator=5.1.1
  - double-conversion=3.3.0
  - epoxy=1.5.10
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - fmt=11.0.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.56.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - glib-tools=2.82.2
  - gmp=6.3.0
  - graph-tool=2.88
  - graph-tool-base=2.88
  - graphite2=1.3.13
  - gtk3=3.24.43
  - harfbuzz=10.2.0
  - hicolor-icon-theme=0.17
  - icu=75.1
  - importlib-metadata=8.6.1
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jedi=0.19.2
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libarchive=3.7.7
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcups=2.3.3
  - libcurl=8.11.1
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgirepository=1.82.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm19=19.1.7
  - liblzma=5.6.4
  - libmamba=2.0.5
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.28
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.46
  - libpq=17.2
  - librsvg=2.58.4
  - libsodium=1.0.20
  - libsolv=0.7.30
  - libsqlite=3.48.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.8.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=2.0.5
  - matplotlib=3.9.4
  - matplotlib-base=3.9.4
  - matplotlib-inline=0.1.7
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - nlohmann_json=3.11.3
  - numba=0.60.0
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pango=1.56.1
  - parso=0.8.4
  - pathspec=0.12.1
  - patsy=1.0.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - pixman=0.44.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - psutil=6.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycairo=1.27.0
  - pycparser=2.22
  - pygments=2.19.1
  - pygobject=3.50.0
  - pyparsing=3.2.1
  - pyside6=6.8.2
  - python=3.9.18
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python_abi=3.9
  - pytz=2024.1
  - pyzmq=26.2.1
  - qhull=2020.2
  - qt6-main=6.8.2
  - readline=8.2
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.8.0
  - sigcpp-3.0=3.6.0
  - simdjson=3.11.6
  - six=1.17.0
  - sparsehash=2.0.4
  - spdlog=1.15.1
  - sqlite=3.32.3
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=16.0.0
  - wayland=1.23.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xextproto=7.3.0
  - xz=5.4.6
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - ansi2html==1.9.2
      - anyio==4.8.0
      - anywidget==0.9.13
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==25.1.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - bleach==6.2.0
      - blessed==1.20.0
      - blinker==1.9.0
      - charset-normalizer==3.4.1
      - cython==3.0.11
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - defusedxml==0.7.1
      - faiss-cpu==1.12.0
      - fastjsonschema==2.21.1
      - filelock==3.17.0
      - flask==3.0.3
      - flatbuffers==25.2.10
      - fqdn==1.5.1
      - fsspec==2025.2.0
      - gast==0.6.0
      - gensim==4.3.3
      - geoopt==0.5.0
      - geopt==0.0.2
      - google-pasta==0.2.0
      - gpustat==1.1.1
      - grpcio==1.70.0
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jinja2==3.1.5
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-dash==0.4.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - keras==3.8.0
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mercator==1.0.0
      - mistune==3.1.2
      - ml-dtypes==0.4.1
      - mpmath==1.3.0
      - namex==0.0.8
      - narwhals==1.27.1
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - ninja==1.11.1.3
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opt-einsum==3.4.0
      - optree==0.14.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - plotly==6.0.0
      - prometheus-client==0.21.1
      - protobuf==5.29.3
      - psygnal==0.12.0
      - pybind11==2.13.6
      - pyclustering==0.10.1.2
      - pynndescent==0.5.13
      - python-json-logger==3.2.1
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.3
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.23.0
      - send2trash==1.8.3
      - smart-open==7.1.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - torch==2.6.0
      - triton==3.2.0
      - types-python-dateutil==2.9.0.20241206
      - umap-learn==0.5.7
      - uri-template==1.3.0
      - urllib3==2.3.0
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
prefix: /nobackup/gogandhi/miniconda3/envs/gensim_mod_env
